param([string]$SourceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")))
$ErrorActionPreference = 'Stop'
function RequireText($Path, $Pattern, $Description) {
  if (!(Test-Path -LiteralPath $Path)) { throw "Missing file for check: $Path" }
  $text = Get-Content -LiteralPath $Path -Raw
  if ($text -notmatch $Pattern) { throw "Missing required forensic directive implementation: $Description ($Pattern) in $Path" }
  Write-Host "Verified: $Description"
}
$aff4 = Join-Path $SourceRoot 'src\parsers\aff4_probe_worker.cpp'
$ios = Join-Path $SourceRoot 'src\parsers\ios_app_db_parser.cpp'
$caseDb = Join-Path $SourceRoot 'src\db\case_db.cpp'
$views = Join-Path $SourceRoot 'src\gui\view_registry.cpp'
$win32 = Join-Path $SourceRoot 'src\gui\win32_gui.cpp'
$runner = Join-Path $SourceRoot 'tools\Run-IosCoreSpotlightFocusedZip.ps1'
RequireText $aff4 'visitedGuidedNodes' 'APFS guided traversal visited-node set'
RequireText $aff4 'GUIDED_INODE_LOOKUP_CYCLE_DETECTED' 'APFS guided inode cycle marker'
RequireText $aff4 'GUIDED_FILE_EXTENT_LOOKUP_CYCLE_DETECTED' 'APFS guided file extent cycle marker'
RequireText $ios 'ripBplistStrings' 'iOS embedded bplist string ripping'
RequireText $ios 'resolveUid' 'iOS bounded NSKeyedArchiver UID reconstruction helper'
RequireText $ios 'tel:' 'iOS tel: identity recovery'
RequireText $ios 'mailto:' 'iOS mailto: identity recovery'
RequireText $ios 'NOTES_RECORDS' 'iOS Notes routing'
RequireText $ios 'LOCATION_RECORDS' 'iOS Location routing'
RequireText $ios 'zcontent' 'iOS Notes/content column catcher'
RequireText $ios 'payload' 'iOS payload column catcher'
RequireText $caseDb 'vw_ios_spotlight_comms_missing_from_ffs' 'CoreSpotlight communication not matched to native DB case schema view'
RequireText $win32 'vw_ios_spotlight_comms_missing_from_ffs' 'CoreSpotlight communication not matched to native DB GUI bootstrap view'
RequireText $views 'vw_ios_spotlight_comms_missing_from_ffs' 'CoreSpotlight communication missing/native DB GUI registration'
RequireText $caseDb 'vw_ios_production_readiness_summary' 'iOS production-readiness schema view'
RequireText $views 'vw_ios_production_readiness_summary' 'iOS production-readiness GUI registration'
RequireText $win32 'vw_ios_production_readiness_summary' 'iOS production-readiness GUI bootstrap view'
RequireText $runner 'ForceContainerHash' 'iOS runner exposes production hash switch'
RequireText $runner 'FullNativeValues' 'iOS runner exposes full native values production switch'
RequireText $runner '--experimental-full-native-values' 'iOS runner passes full native values CLI flag'
RequireText $runner 'MaterializeIosSupportDb' 'iOS runner exposes bounded support materialization switch'
RequireText (Join-Path $SourceRoot 'src\core\hash.cpp') 'sha256FileWithProgress' 'SHA256 progress-capable hash helper'
RequireText (Join-Path $SourceRoot 'src\app\app_runner.cpp') 'original_container_hash_progress' 'source-container hash progress run-status marker'
RequireText (Join-Path $SourceRoot 'src\app\app_runner.cpp') 'complete_aff4_apfs_staged_storev2_validation_probe' 'AFF4/APFS staged Store-V2 validation completion stage'
RequireText (Join-Path $SourceRoot 'src\app\app_runner.cpp') 'AFF4_APFS_STAGED_STOREV2_' 'AFF4/APFS staged Store-V2 decode mode summary marker'
RequireText (Join-Path $SourceRoot 'src\app\app_runner.cpp') 'result.databaseCandidateCount = stagedParserResult.candidates.size\(\)' 'AFF4/APFS staged parser candidates reflected in case_summary'
RequireText (Join-Path $SourceRoot 'src\app\app_runner.cpp') 'Store discovery counts in case_summary must describe the database set' 'preserved Store-V2 rediscovery counts reflected in case_summary'
RequireText (Join-Path $SourceRoot 'src\parsers\native_storedb_parser.cpp') 'Validation mode must remain evidence-preserving' 'FullValues fallback to bounded raw probes when structured metadata is empty'
RequireText (Join-Path $SourceRoot 'src\parsers\native_storedb_parser.cpp') 'kvStmt.bind\(8, effectiveFullPath\)' 'raw key/value full_path uses metadata/reconstructed effective path'
RequireText (Join-Path $SourceRoot 'src\parsers\native_storedb_parser.cpp') 'if \(parts.empty\(\)\) return \{\};' 'parent-inode reconstruction does not invent root path for unnamed non-root records'
Write-Host 'Forensic directive verification passed for V1.6.35.'
